version: '3'

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql


  node:
    build: .
    command: "npm run dev"
    environment:
      - NODE_ENV=production
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"

volumes:
  db: